### ISSUE TITLE
Version constraint clashes while building with stack

### ISSUE THREAD

**Issue by herrhotzenplotz** [tsoding/kgbotka#137]
**Steps to reproduce:**
```bash
$ stack init
```
**Observed behaviour:**
+ stack cannot select a resolver that satisfies all the dependencies and their version constraints from the cabal file

**Steps that may resolve the issue:**
+ Check [Stack output](https://gist.github.com/herrhotzenplotz/ffef8bfa7b69a680329a8b3ce1be3e4a) and change versions of packages so that one resolver satisfies all constraints

**Comment by rexim** [comment]
@herrhotzenplotz To be honest, I stopped using stack long time ago because I always had these kind of problems with it. These days I just use `cabal v2-build` as I described in [Quick Start](https://github.com/tsoding/kgbotka#quick-start). Have you tried it? Maybe it will work for you as a temporary measure.

I have no idea how to fix the stack problem, I'm really sorry! Feel free to take this issue and submit a pull request when you figure it out. I'll be super glad to merge it!
